<script setup lang="ts">
import type {ConditionTree} from '@/types/conditions';
const props=withDefaults(defineProps<{modelValue:ConditionTree;depth?:number}>(),{depth:1});const emit=defineEmits<{'update:modelValue':[ConditionTree]}>();
function kind(event:Event){const op=(event.target as HTMLSelectElement).value;if(op==='and'||op==='or'){emit('update:modelValue',{op,children:'children'in props.modelValue?props.modelValue.children:[{op:'mainline'},{op:'change_above',value:1}]});}else if(op==='change_above'||op==='change_below'){emit('update:modelValue',{op,value:'value'in props.modelValue?props.modelValue.value:1});}else if(op==='mainline'){emit('update:modelValue',{op});}}
function child(i:number,value:ConditionTree){if('children'in props.modelValue){const children=props.modelValue.children.map((v,n)=>n===i?value:v);emit('update:modelValue',{op:props.modelValue.op,children});}}
function add(){if('children'in props.modelValue)emit('update:modelValue',{op:props.modelValue.op,children:[...props.modelValue.children,{op:'change_above',value:1}]});}
function remove(i:number){if('children'in props.modelValue)emit('update:modelValue',{op:props.modelValue.op,children:props.modelValue.children.filter((_,n)=>n!==i)});}
function number(event:Event){if('value'in props.modelValue){const value=Number((event.target as HTMLInputElement).value);emit('update:modelValue',{op:props.modelValue.op,value:Number.isFinite(value)?value:0});}}
</script>
<template><div class="condition-node" :data-depth="depth">
<div class="condition-node-head"><select :value="modelValue.op" :aria-label="'第'+depth+'层条件类型'" @change="kind"><option value="and" :disabled="depth>=4">全部满足（AND）</option><option value="or" :disabled="depth>=4">任一满足（OR）</option><option value="mainline">强势主线领涨</option><option value="change_above">涨跌幅至少</option><option value="change_below">涨跌幅至多</option></select><template v-if="'value'in modelValue"><input :value="modelValue.value" type="number" min="-30" max="30" step="0.1" aria-label="涨跌幅百分比" @input="number"><span>%</span></template></div>
<div v-if="'children'in modelValue" class="condition-node-children"><div v-for="(node,i) in modelValue.children" :key="i" class="condition-child"><ConditionTreeEditor :model-value="node" :depth="depth+1" @update:model-value="child(i,$event)"/><button class="condition-remove" :disabled="modelValue.children.length<=2" :aria-label="'移除第'+(i+1)+'项条件'" @click="remove(i)">移除</button></div><button :disabled="modelValue.children.length>=4" @click="add">添加一项</button></div>
</div></template>
<style scoped>
.condition-node{border:1px solid var(--color-border-0);border-radius:8px;padding:8px;background:var(--color-surface-1);min-width:0}.condition-node-head{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.condition-node-head select{max-width:100%;min-width:0}.condition-node-head input{width:72px;min-width:0}.condition-node select,.condition-node input,.condition-node button{background:var(--color-surface-1);color:var(--color-text-primary);border:1px solid var(--color-border-0);border-radius:6px;padding:5px;font-size:12px}.condition-node button{cursor:pointer}.condition-node button:disabled{opacity:.4}.condition-node-children{display:grid;gap:6px;margin-top:8px;padding-left:8px;border-left:2px solid var(--color-accent-dim)}.condition-child{display:flex;gap:4px;align-items:start;min-width:0}.condition-child>.condition-node{flex:1}.condition-remove{font-size:var(--text-xs);white-space:nowrap}.condition-node[data-depth="4"]{padding:5px}@media(max-width:540px){.condition-node-children{padding-left:3px}.condition-child{display:grid;grid-template-columns:minmax(0,1fr)}.condition-remove{justify-self:end}}
</style>
