<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { invoke } from '@tauri-apps/api/core';
import { NModal } from 'naive-ui';
import {describeCondition,type ConditionTree} from '@/types/conditions';
import { modelScore } from '@/types/research';
const props=defineProps<{show:boolean;eventKey:string|null}>();const emit=defineEmits<{'update:show':[boolean]}>();
interface Snapshot {schema:string;event_key:string;event:string;symbol:string;model_name:string;model_id:string;preset:string;as_of:string;checked_at:string;production_admission:false;message:string;evidence:{condition_tree?:ConditionTree;condition_facts?:{intraday:boolean|null;mainline:boolean|null;change_pct:number|null};candidate?:{score:number;close:number;threshold:number};model_group?:Record<string,unknown>;intraday_snapshot?:Record<string,unknown>;mainline_snapshot?:{sector_name?:string;as_of?:string;strong?:boolean;fingerprint?:string}}}
const snapshot=ref<Snapshot|null>(null);const error=ref('');const busy=ref(false);let version=0;
const kind=computed(()=>snapshot.value?.event==='conditions_confirmed'?'条件新成立':snapshot.value?.event==='model_invalidated'?'盘后模型条件失效':snapshot.value?.event==='conditions_invalidated'?'组合条件失效':'盘中形态失效');
const preset=computed(()=>({model_hit:'模型新命中 / 失效',model_confirm:'模型＋盘中确认',model_mainline_confirm:'模型＋主线＋盘中确认',custom:'自定义组合'}[snapshot.value?.preset??'']??'未知条件'));
watch(()=>[props.show,props.eventKey] as const,async([show,key])=>{const current=++version;if(!show||!key)return;busy.value=true;error.value='';snapshot.value=null;try{const row=await invoke<Snapshot>('get_model_condition_event',{eventKey:key});if(row.schema!=='model-condition-event-v1'||row.event_key!==key||row.production_admission!==false)throw Error('通知证据身份不一致');if(current===version)snapshot.value=row;}catch(e){if(current===version)error.value=String(e);}finally{if(current===version)busy.value=false;}},{immediate:true});
</script>
<template>
  <NModal :show="show" preset="card" title="模型条件 · 触发时证据" :style="{width:'min(760px,94vw)',maxHeight:'88vh',overflow:'auto'}" @update:show="emit('update:show',$event)">
    <div class="condition-evidence"><p v-if="busy">读取已保存的触发证据…</p><p v-if="error" class="error">{{error}}</p><template v-if="snapshot"><h3>{{snapshot.symbol}} · {{kind}}</h3><p>{{snapshot.model_name}} · {{preset}}</p><p>模型截止 {{snapshot.as_of}} · 触发核验 {{snapshot.checked_at}}</p><p>{{snapshot.message}}</p><div v-if="snapshot.evidence.candidate" class="evidence-score"><b>分数 {{modelScore(snapshot.evidence.candidate.score,snapshot.model_id)}}</b><span>阈值 &gt; {{modelScore(snapshot.evidence.candidate.threshold,snapshot.model_id)}}</span><span>冻结收盘 {{snapshot.evidence.candidate.close}}</span></div><p v-else>最新完成日该股不再满足模型条件，未用零分替代缺失评分。</p><p v-if="snapshot.evidence.intraday_snapshot">分钟状态 {{snapshot.evidence.intraday_snapshot.state}} · 观测截止 {{snapshot.evidence.intraday_snapshot.checked_at}}</p><p v-if="snapshot.evidence.mainline_snapshot">关联主线 {{snapshot.evidence.mainline_snapshot.sector_name || '已保存主线'}} · {{snapshot.evidence.mainline_snapshot.as_of}} · 强势核验 {{snapshot.evidence.mainline_snapshot.strong?'通过':'未通过'}}</p><p v-if="snapshot.evidence.condition_tree">范围：该股票模型命中 且 {{describeCondition(snapshot.evidence.condition_tree)}}</p><p v-if="snapshot.evidence.condition_facts">当时条件：盘中确认 {{snapshot.evidence.condition_facts.intraday===null?'未知':snapshot.evidence.condition_facts.intraday?'满足':'未满足'}} · 强势主线 {{snapshot.evidence.condition_facts.mainline===null?'未知':snapshot.evidence.condition_facts.mainline?'满足':'未满足'}} · 涨跌幅 {{snapshot.evidence.condition_facts.change_pct?.toFixed(2)??'--'}}%</p><p class="note">这是触发时保存的研究观察，查看不会重新计算或调用 AI。分数不是胜率，也未获得实盘准入。</p><details><summary>分钟形态、价位、主线和来源指纹</summary><pre>{{JSON.stringify(snapshot,null,2)}}</pre></details></template></div>
  </NModal>
</template>
<style scoped>
.condition-evidence{font-size:13px;line-height:1.8;color:var(--color-text-primary,#26354a)}.condition-evidence h3{font-size:16px;margin:0 0 8px}.evidence-score{display:flex;gap:14px;flex-wrap:wrap;background:var(--color-surface-2,#f5f7fb);border-radius:9px;padding:12px}.note{color:var(--color-text-secondary,#69778c);font-size:12px}.condition-evidence pre{max-height:360px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;font-size:var(--text-xs);font-family:var(--font-sans)}.condition-evidence summary{cursor:pointer}.error{color:var(--color-error,#13714e);overflow-wrap:anywhere}
</style>
